### ISSUE TITLE
Fonts intermittently don't load in development environment

### ISSUE THREAD

**Issue by jbritain** [eddb2-0/EDDB-2.0-frontend#61]
Sometimes when running `yarn dev`, the console throws up the following errors
```
FetchError: request to https://fonts.googleapis.com/css2?family=Rubik:wght@300..900&display=swap failed, reason: 
    at ClientRequest.<anonymous> (/home/joshua/Documents/Programming/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'system',
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH'
}
- error Failed to download `Rubik` from Google Fonts. Using fallback font instead.
FetchError: request to https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap failed, reason: 
    at ClientRequest.<anonymous> (/home/joshua/Documents/Programming/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:511:9) {
  type: 'system',
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH'
}
- error Failed to download `Orbitron` from Google Fonts. Using fallback font instead.
```

The result of this is that the site resorts to using the default `serif` font, as shown
![image](https://github.com/ed-pilots-network/frontend/assets/50422789/2df78e3e-e596-41c3-8586-a20e67c67a63)

Apart from the fact that the fonts don't load, we ought to also ensure that the fallback font is a sans serif font as opposed to a serif one.

**Comment by nitishdhar** [comment]
This is still happening - Mac, Edge Browser running yarn dev

![Screen Shot 2023-08-26 at 9 14 47 PM](https://github.com/ed-pilots-network/frontend/assets/1340144/4bef02a2-0d5b-4e9a-8d91-a69162269da0)

**Comment by nitishdhar** [comment]
It seems to work fine with --turbo but happens when not using turbo.

**Comment by nitishdhar** [comment]
Another related issue for the fetch failure - https://github.com/vercel/next.js/issues/45080

**Comment by nitishdhar** [comment]
@jbritain - so there are two issues here - 

1. No console error but the fonts don't render in dev environment
2. Console error for fetch of the fonts from google

For 1., I have pushed this fix https://github.com/ed-pilots-network/frontend/pull/95 but for 2., there isn't a clean fix yet (https://github.com/vercel/next.js/issues/45080) but there's a workaround, just delete you `.next` folder and and run `yarn dev` again.

**Comment by fuomag9** [comment]
This still does not work for me, using curl via the terminal works fine so it's not a network issue

**Comment by ziin** [comment]
> It seems to work fine with --turbo but happens when not using turbo.

I had this fetch problem only in development and I fixed it using the `--turbo` flag.

**Comment by sumairq** [comment]
Deleting the `.next` folder and regenerating it does not work for me.
Adding `--tubo` flag to my dev script works ` "dev": "next dev --turbo",`
However, we should not be needing the turbopack just so the fonts load properly in the development environment. I hope this issue gets fixed soon.

I am running `"next": "14.0.4" `  with node `v20.6.1`.

**Comment by aslink87** [comment]
I finally got this to happen to me as well. I've made a pr to switch entirely to local fonts. #137
